### ISSUE TITLE
[Github integration] Cannot sign in 

### ISSUE THREAD

**Issue by thefoxis** [hubbleio/hubble.io#28]
Can't sign in using log in/sign in button or in modals.

**Comment by thefoxis** [comment]
@pgte 

`[Error: Github replied with status code 401 to URL https://api.github.com/user?access_token=undefined]`

**Comment by pgte** [comment]
Thanks, I'll look into this.

**Comment by pgte** [comment]
@karolinaszczur , something's wrong with the github response for your case, but I'm not sure what it is.
We'll have to do a bit of remote debugging :/

I've added some console debugging, @karolinaszczur, please pull from hubble.io and try to login and give me the server logs.

Thanks!

**Comment by thefoxis** [comment]
@pgte from console:

`response body form github: access_token=024e946816a824bac1ee9c1634cebf600cd941a4&token_type=bearer`

**Comment by pgte** [comment]
That's very strange.
@karolinaszczur, what node version are you running?

Also, I've pushed something that could fix it, it's kind of a long shot, but please try to update hubble.io, relaunching nodeguides and trying to login again.

Thanks.

**Comment by thefoxis** [comment]
Still not working..

```
Error: Github expected response status code is 500URL: https://api.github.com/markdown?mode=gfm,  body:Server Error
    at Request._callback (/Users/karolina/workroot/git/hubble.io/lib/github.js:20:13)
    at Request.init.self.callback (/Users/karolina/workroot/git/hubble.io/node_modules/request/main.js:120:22)
    at Request.EventEmitter.emit (events.js:91:17)
    at Request.<anonymous> (/Users/karolina/workroot/git/hubble.io/node_modules/request/main.js:633:16)
    at Request.EventEmitter.emit (events.js:88:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/Users/karolina/workroot/git/hubble.io/node_modules/request/main.js:595:14)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1356:20)
path.existsSync is now called `fs.existsSync`.
[hubble] Starting http server on  0.0.0.0:8080
Hubble.IO started
response body form github: access_token=024e946816a824bac1ee9c1634cebf600cd941a4&token_type=bearer
```

**Comment by pgte** [comment]
That one looks like an error on startup where the Github API is crapping out and returning a 500...

Can you try that again? Sorry... :/

**Comment by thefoxis** [comment]
Still error and cannot log in:

`response body form github: access_token=024e946816a824bac1ee9c1634cebf600cd941a4&token_type=bearer`

**Comment by pgte** [comment]
:(

@karolinaszczur I think you didn't get to tell me: what node version?

**Comment by pgte** [comment]
@karolinaszczur any news on thenode version where this is happening?

**Comment by julianduque** [comment]
Fixed in https://github.com/hubbleio/hubble.io/pull/43
